apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: kseniasavkina/admin:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: spring.boot.admin.context-path
              value: /admin
