spring:
  application:
    name: comments-api
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url: ${SPRING_ADMIN:http://localhost:8080/}

management:
  endpoints:
    web:
      exposure:
        include: "*"